<?php

$links = [
	'Razor' => 'https://youtu.be/h8WbZNZdD6s',
	'Chongyun' => 'https://youtu.be/qEg9fzclOpY',
	'Kamisato Ayaka' => 'https://youtu.be/8yxvwNEnLTA',
	'Albedo' => 'https://youtu.be/3fNZJsZV7Bk',
	'Mona' => 'https://youtu.be/Xkw7Tjl21FA',
	'Ningguang' => 'https://youtu.be/zep-iBnwJxU',
	'Amber' => 'https://youtu.be/dcgAi2tE8wI',
	'Yanfei' => 'https://youtu.be/W6uMcpOte7s',
	'Klee' => 'https://youtu.be/5JA5yz6sCck',
	'Kuki Shinobu' => 'https://youtu.be/hCMJZLrf2dM',
	'Shikanoin Heizou' => 'https://youtu.be/T5IxgFdzaKo',
	'Tartaglia' => 'https://youtu.be/J_e0Pci22u0',
	'Hu Tao' => 'https://youtu.be/7T3HElrXPWw',
	'Kujou Sara' => 'https://youtu.be/263Mzex7pgA',
	'Barbara' => 'https://youtu.be/00SlQ-acLdA',
	'Yae Miko' => 'https://youtu.be/aboVUNBPpIM',
	'Raiden Shogun' => 'https://youtu.be/fCfZQxsVmww',
	'Yoimiya' => 'https://youtu.be/bpwui7znyvw',
	'Venti' => 'https://youtu.be/oT8aM0Ia9PE',
	'Lisa' => 'https://youtu.be/yhbN8FxDWWc',
	'Arataki Itto' => 'https://youtu.be/e_RiOrih-Pg',
	'Fischl' => 'https://youtu.be/99m0K_ifQ5U',
	'Shenhe' => 'https://youtu.be/1WK_AGPUjH8',
	'Yaoyao' => 'https://youtu.be/bzCH_cauSzs',
	'Qiqi' => 'https://youtu.be/biU24B-Poq0',
	'Bennett' => 'https://youtu.be/3hIM3lix_Lg',
	'Jean' => 'https://youtube.com/shorts/9z15Z1alWDk?feature=share',
	'Aloy' => 'https://youtube.com/shorts/TgkTHmCXEvI?feature=share',
	'Xiao' => 'https://youtube.com/shorts/iwzpelKrVYg?feature=share',
	'Collei' => 'https://youtube.com/shorts/polb25MyWHg?feature=share',
	'Gorou' => 'https://youtube.com/shorts/h3rm7gh1l8s?feature=share',
	'Diluc' => 'https://youtube.com/shorts/QNisWyx-3zE?feature=share',
	'Yun Jin' => 'https://youtube.com/shorts/jC8gq9j5Unw?feature=share',
];
